version: '3.8'

services:
  web:
    build:
      context: ./docker/web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    restart: always

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: storylog
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  # Add this line for data persistence
    restart: always

  adminer:
    build: 
      context: ./docker/adminer
    ports:
      - "8080:8080"
    restart: always
    
volumes:
  db_data:  # Define the named volume
