#!/usr/bin/php
<?php

/**
 *
 * Author: Henry
 *
 * This script will generate a JSON file for storylog
 */

// It exits if the interface is not CLI
if (php_sapi_name() !== 'cli') {
    exit;
}

// Config name
$config = "storylog.json";

// Warn user if the config exists and allowed to override
if (file_exists($config)) {
    echo "Warning: The existing data in config will be overwritten!\n";
    $check = readline("[?] Want to override the existing config? [Y/n] ");
    if ($check == "y" | $check == "Y" | $check == "") {
        echo "[*] Overwriting the existing config...\n";
    } else {
        exit;
    }
} else {
    echo "Welcome to photogram config generator!\n";
}

echo "\n==> Enter the following details to generate the config\n\n";

// Prompts to get the data
$server_address = readline("-> Server address: ");
$db_user = readline("-> Database username: ");
$db_pass = readline("-> Database password: ");
$db_name = readline("-> Database name: ");
$storage_path = readline("-> Enter storage path: ");

echo "\n==> Enter the following prompts to setup mail server:\n";

$smtp_host = readline("-> Enter SMTP Host: ");
$smtp_auth_user = readline("-> Enter SMTP auth user: ");
$smtp_auth_pass = readline("-> Enter SMTP auth pass: ");

$domain_name = readline("-> Enter domain name: ");

$contents = "{
    \"db_server\": \"{$server_address}\",
    \"db_user\": \"{$db_user}\",
    \"db_pass\": \"{$db_pass}\",
    \"db_name\": \"{$db_name}\",
    \"storage_path\": \"{$storage_path}\",
    \"smtp_host\": \"{$smtp_host}\",
    \"smtp_auth_user\": \"{$smtp_auth_user}\",
    \"smtp_auth_pass\": \"{$smtp_auth_pass}\",
    \"domain_name\": \"{$domain_name}\"
}
";

file_put_contents("{$config}", "{$contents}");

echo "\n==> Config generated!\n\n";
